### PR TITLE
new task flag: copy all in variables into task execution context

### PR DESCRIPTION
**Pull request by brig**

### CODE REVIEW

**Comment by atanasenko** [comment]
Isn't it something that SubProcess#useSeparateContext handles in some way?

**Comment by ibodrov** [comment]
@atanasenko huh, good point. We need to support the opposite behavior in Service/ScriptTask - visibility of all variables of a parent context in addition to IN variables.
And I think, for consistency's sake, we need to add `#useParentContext` (name suggestions are welcome!) to Service/ScriptTask instead of using a `Configuration` switch.

**Comment by atanasenko** [comment]
`useSeparateContext` means that subProcess (or callActivity) will see those vars, but will not be able to modify them.

I Didn't know that when IN vars are specified all others are effectively ignored

**Comment by atanasenko** [comment]
Yea, I think this flag should come along with tasks themselves, whether to allow them to see parent context in addition to whatever gets passed as IN. 

So given the 4 possible situations:
1. no IN vars, no parentContext
2. no IN vars, with parentContext
3. yes IN vars, no parentContext
4. yes IN vars, with parentContext
Engine currently passes parentContext if no IN vars are there (2), but if IN vars are present, it ignores parentContext.
Maybe we should, for consistency, change the default it to either use parentContext or not, irregardless of whether IN vars are specified or not? And then allow controlling it with a separate flag.
This will break backwards compatibility though.

**Pull request merged**
